AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  avdefinitionsupdate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: download-definitions.lambdaHandleEvent
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 600
      Role: 'arn:aws:iam::550239480852:role/eb-lambda-s3-execution-role'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(3 hours)
      Environment:
        Variables:
          CLAMAV_BUCKET_NAME: clamav-definitions-bucket
          PATH_TO_AV_DEFINITIONS: lambda/s3-antivirus/av-definitions
      Layers:
        - >-
          arn:aws:lambda:us-west-2:550239480852:layer:clamav-dependencies-layer:6
